version: '3.8'
services:
  trello:
#    image: negaranabestani/trello
    image: trello
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    ports:
      - '8000:8000'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    ports:
#      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
