# Generated by Django 5.0.6 on 2024-06-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('role', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
