# Generated by Django 5.0.6 on 2024-06-28 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_role_permissions'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='workspace.workspace'),
        ),
        migrations.AlterField(
            model_name='userworkspacerole',
            name='role',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userworkspacerole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_workspace_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userworkspacerole',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_workspace_roles', to='workspace.workspace'),
        ),
    ]
