# Generated by Django 5.0.6 on 2024-06-28 19:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0005_alter_userworkspacerole_user_and_more'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userworkspacerole',
            unique_together={('user', 'workspace')},
        ),
    ]
