# Generated by Django 5.0.6 on 2024-06-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
