# Generated by Django 5.0.6 on 2024-06-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subscribers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
